<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> <?=$data['title']?> </title>
    <link rel="stylesheet" type="text/css" href="/css/polideportivo-global.css">
    <style>
    *{
    	box-sizing: border-box;
    }
    	main{
    		max-width: 400px;
    		margin: 0 auto;
    		padding: 1em;
    	}
		header > div {
			display: flex;
			align-items: center;
   		}
		header > div > h1{
			margin-right: auto;
			margin-top: .3em;
			padding: 5px;
			background-color:lightblue;
			border-radius: 4px;
			color: white;
		}
		header > div > h1 > a{
			color: black;
			text-decoration: none;
		}
		header > div > h1 > a:hover{
			color: white;
			text-decoration: none;
		}
		header > div > a:nth-child(2){
			display: inline-block;
			margin-right: 2em;
		}
		nav	{
			text-align: center;
		}
		.post{
			border-left: 2px solid silver;
			border-right: 2px solid silver;
			padding-left: 1em;
			padding-right: 1em;
		}
		
		.titulo-campo::first-letter{
            color:red;
		}
		
		.error-campo{
		  color: red;
		}
		
		.campo{
		  
		 }
		 
		 textarea{
		  width:100%;
		  height: 100px;
		  resize: none;
		 }
		 
		 input{
		 width:100%;
		 }

    </style>
</head>
<body>
	<main>
		<header>
			<div>
				<h1><a href="/foro/index/">FORO MVC</a></h1>
				<a href="/foro/registro/">Registrate</a>
				<a href="/foro/entrar/">Entrar</a>
			</div>
		</header>
		<hr>
		<nav>
			<h3><a href="/foro/crear/">¡Crea un post!</a></h3>
		</nav>
		<hr>
<!-- Al ser el phtml base, se podra agregar el Js aqui, para todas las paginas que lo necesiten (desplegable del nav...) -->
    <?= $data['contenido']?>
	</main>
</body>
</html>
