<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> <?=Config::get('site.name')?> </title>
    <!--<link rel="stylesheet" href="/css/polideportivo-global.css">-->
</head>
<body>

<header>
    <?php 
        if (isset($data["nav_admin"])) { 
            include('comunes/nav_admin.phtml');
        }else if(isset($data["nav_cliente"])){
            require('comunes/nav_cliente.phtml');
        }
    ?>
</header>

<main>
    <div class="container">
    <?= $data['contenido']?>
    </div>
</main>
<footer>
    <?= include('comunes/footer.phtml');?>
</footer>
</body>
</html>
