<?php $user = $data['user']; ?>
<div class="container">
		<main>
 		<h3>
 			Cofiguracion
 		</h3>
 		<hr>
			<section>
				<article class="row">
					<div class="col-md-2">
						<figcaption>
							<caption>
								<a href="">Cambiar foto</a>
							</caption>
							<figure>
								<img src="/img/users/<?=$user->imagen_perfil?>" alt="imagen_perfil">
							</figure>
							<caption>
								<h4><?=$user->nombre_usuario?></h4>
							</caption>
						</figcaption>
						<div>
							<ul>
 								<li><a href="/usuario/configuracion_perfil">Mi perfil</a></li>
 								<li><a href="/usuario/configuracion_cuenta">Configuracion</a></li>
 								<li><a href="/usuario/facturacion">Facturación</a></li>
 								<li><a href="/usuario/eliminar_cuenta">Eliminiar mi cuenta</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-10">
						<div class="row">
          <h4>Configuracion de mi cuenta</h4>
          <p><span>Email: </span><span><?=$user->email?></span>
            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-pencil"></span> Editar
            </button>
          </p>
          <p><span>Nombre: </span><span><?=$user->nombre?></span></p>
          <p><span>Apellidos: </span><span><?=$user->apellido_1?> <?=$user->apellido_2?></span></p>
          <p><span>Direccion: </span><span><?=$user->direccion?></span>
            <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-pencil"></span> Editar
            </button>
          </p>
       
          <h4>Seguridad</h4>
          <h4>Cambiar contraseña:</h4>
          <form action="/usuario/cambio_contrasena" method="POST">
          	<div><?php if(!empty($data["error"])) echo $data["error"];?></div>
          	<div><?php if(!empty($data["contrasenaCambiada"])) echo $data["contrasenaCambiada"];?></div>
			          	
          	<div>
          		<label>Contraseña actual:<input type="password" name="pass_actual"></label>
          	</div>
          	<div>
          		<label>Nueva contrasena:<input type="password" name="pass_nueva_1" ></label>
          	</div>
          	<div>
          		<label>Repite la nueva contraseña:<input type="password" name="pass_nueva_2"></label>
          	</div>
          	<div><input type="submit" name="Enviar" value="Cambiar contraseña"></div>
          </form>
						</div>
					</div>
				</article>
			</section>
		</main>
	</div>