<link rel="stylesheet" href="/css/reserva_pista.css">
<link rel="stylesheet" href="/css/reserva_clase.css">
<?php 

$deporte = array_values($_SESSION["listaDeportes"]);
$dep ="";
foreach ($deporte as $value ) {
    if ($value["id_deporte"] == $_POST["id_deporte"]) {
      $dep = $value["nombre_deporte"];
    }
}

$res = ModelUsuario::getInstalacion($_POST["id_deporte"]);
$id_instalacion = $res[0]["id_instalacion"];
$precio = $res[0]["precio_hora"];
$nombreCompleto = $data['user']->nombre." ".$data['user']->apellido_1." ".$data['user']->apellido_2;
$email = $data['user']->email;
$id_pista = $res[0]["id_pista"];

?>
    <div class="container">
      <main class="jumbotron">
      <form action="/usuario/confirmarPago/" method="post">
        <div class="row">
        <h2 class="text-center text-uppercase">Confirmación de datos.</h2>
        <div class="col-md-9 col-md-offset-3">
        
          <div class="row">
            <div class="col-md-1 col-md-offset-1">
              <p>
                <span>Nombre:</span>
              </p>
            </div>
            <div class="col-md-9 col-md-offset-1">
              <p><?=  $nombreCompleto?></p>
              <input type="hidden" name="nombre" value="<?= $nombreCompleto?>">
            </div>
          </div>

          <div class="row">
            <div class="col-md-1 col-md-offset-1">
              <p>
                <span>Actividad:</span>
              </p>
            </div>
            <div class="col-md-9 col-md-offset-1">
              <p><?= $dep?></p>
              <input type="hidden" name="deporte" value="<?= $dep?>">
            </div>
          </div>

          <div class="row">
            <div class="col-md-1 col-md-offset-1">
              <p>
                <span>Instalación:</span>
              </p>
            </div>
            <div class="col-md-9 col-md-offset-1">
              <p><?= $id_instalacion?></p>
              <input type="hidden" name="instalacion" value="<?= $id_instalacion?>">
            </div>
          </div>

          <div class="row">
            <div class="col-md-1 col-md-offset-1">
              <p>
                <span>Fecha:</span>
              </p>
            </div>
            <div class="col-md-9 col-md-offset-1">
              <p><?= $_POST["fecha"]?></p>
              <input type="hidden" name="fecha" value="<?= $_POST["fecha"]?>">
            </div>
          </div>

          <div class="row">
            <div class="col-md-1 col-md-offset-1">
              <p>
                <span>Hora:</span>
              </p>
            </div>
            <div class="col-md-9 col-md-offset-1">
              <p>16:00 a 16:59</p>
              <input type="hidden" name="hora" value="16:00 16:59">
            </div>
          </div>

          <div class="row">
            <div class="col-md-1 col-md-offset-1">
              <p>
                <span>Email:</span>
              </p>
            </div>
            <div class="col-md-9 col-md-offset-1">
              <p><?= $email?></p>
              <input type="hidden" name="email" value="<?= $email?>">
            </div>
          </div>

          <div class="row">
            <div class="col-md-1 col-md-offset-1">
              <p>
                <span>Precio:</span>
              </p>
            </div>
            <div class="col-md-9 col-md-offset-1">
              <p><?= $precio?> €</p>
              <input type="hidden" name="precio" value="<?= $precio?>">
            </div>
          </div>
          <input type="hidden" name="id_pista" value="<?= $id_pista?>">          
        </div>
        </div>
        <input type="submit" value="Continuar" class="btn btn-primary btn-block">
          <!-- Pasos de reserva / footer -->
          <div class="pasos-reserva">
            <div class="row">
              <div class="col-md-7 col-md-offset-3">
                <div class="row">
                  <div class="col-md-12">
                    <div class="col-md-4"><span class="circulo ">1</span></div>
                    <div class="col-md-4"><span class="circulo paso-actual">2</span></div>
                    <div class="col-md-4"><span class="circulo">3</span></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        
      </form>
      </main>
    </div>
    