<?php $user = $data['user']; ?>
<?php $prefs = $data['user_prefs'] ?>
<?php $clases = $data['clases'] ?>
<div class="container">
 		<main>
	 		<h3>
	 			Mi perfil
	 		</h3>
	 		<hr>
 			<section>
 				<article class="row">
 					<div class="col-md-2">
 						<figcaption>
 							<caption>
 								<a href="">Cambiar foto</a>
 							</caption>
 							<figure>
 								<img src="/img/users/<?=$user->imagen_perfil?>" alt="imagen_perfil">
 							</figure>
 							<caption>
 								<h4>Andres Lopez Guzman</h4>
 							</caption>
 						</figcaption>
 						<div>
 							<ul>
 								<li><a href="/usuario/configuracion_perfil">Mi perfil</a></li>
 								<li><a href="/usuario/configuracion_cuenta">Configuracion</a></li>
 								<li><a href="/usuario/facturacion">Facturación</a></li>
 								<li><a href="/usuario/eliminar_cuenta">Eliminiar mi cuenta</a></li>
 							</ul>
 						</div>
 					</div>
 					<div class="col-lg-10">
 						<div class="row">
  							<h4> Mis deportes favoritos</h4>
  							<p><?=$prefs->deportes_favoritos ?> </p>
                 <button type="button" class="btn btn-default btn-sm">
                  <span class="glyphicon glyphicon-pencil"></span> Editar
                </button>
  							<br>
  							<br>
  							<h4> Clases en las que estoy </h4>
  							<p><p> <?=$clases ?> </p></p>
  							<br>
  							<br>
  							<h4> Sobre mi</h4>
  							<p><?=$prefs->comentarios ?></p>
                 <button type="button" class="btn btn-default btn-sm">
                  <span class="glyphicon glyphicon-pencil"></span> Editar
                </button>
 						</div>
 					</div>
 				</article>
 			</section>
 		</main>
 	</div>