<?php $user = $data['user']; ?>
<?php $img = $data['img_perfil'] ?>
<div class="container">
	<main>
		<h3>
		     Eliminar cuenta
		</h3>
		<hr>
		<section>
			<article class="row">
				<div class="col-md-2">
					<figcaption>
						<caption>
							<a href="">Cambiar foto</a>
						</caption>
						<figure>
							<img src="/img/users/<?=$img?>" alt="imagen_perfil" style="width: 80%">
						</figure>
						<caption>
							<h4><?=$user->nombre?> <?=$user->apellido_1?> <?=$user->apellido_2?>  </h4>
						</caption>
					</figcaption>
					<div>
						<ul>
							<li><a href="/usuario/configuracion_perfil">Mi perfil</a></li>
                                <li><a href="/usuario/configuracion_cuenta">Configuracion</a></li>
                                <li><a href="/usuario/facturacion">Facturación</a></li>
                                <li><a href="/usuario/eliminar_cuenta">Eliminiar mi cuenta</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-10">
					<div class="row">
    <p> La eliminacion de la cuenta será permante y no podras recuperar tu cuenta. </p>
<br>
            <form action="/usuario/eliminar" method="POST">
            <div><?php if(!empty($data["error"])) echo $data["error"];?></div>
            <div>
                <label>Introduce tu contraseña:<input type="password" name="pass_actual"></label>
            </div>
            
            <div><input type="submit" name="Enviar" value="Eliminar mi cuenta"></div>
          </form>
					</div>
				</div>
			</article>
		</section>
	</main>
</div>