<?php $user = $data['user']; ?>
<?php $clases = $data['clases'] ?>
<?php $prefs = $data['user_prefs'] ?>
<?php $img = $data['img_perfil'] ?>
<div class="container">
            <!--
            <div class="contenedor-imagen" id="imgGallary">
                <h3>Contenido</h3>
                <img src="../../public/img/tennis_bg.jpg" alt="Tennis">
                <img src="../../public/img/swpool_bg.jpg" alt="sw">
                <img src="../../public/img/soccer_bg.jpg" alt="fut">
            </div>
            -->
            <div class="row jumbotron">
                <div class="col-md-4">
                    <figcaption class="text-center">
                        <figure>
                            <img src="/img/users/<?=$img?>" alt="imagen_perfil">
                        </figure>
                    </figcaption>
                </div>
                <div class="col-md-8">
                    <h3><?=$user->nombre?> <?=$user->apellido_1?> <?=$user->apellido_2?> (<?=$user->nombre_usuario?>)</h3>
                    <!--<h3>Andres Lopez Guzman (Andrew007)</h3>-->
                    <span><?=ModelUsuario::calcularEdad($user->fecha_nacimiento)?> años</span>
                    <h4>Clases en las que estoy </h4>
                    <?=$clases ?> 
                    <h4> Mis deportes favoritos</h4>
                    <?=$prefs->deportes_favoritos ?>
                    <h4> Sobre mi</h4>
                    <?=$prefs->comentarios ?>
                </div>
            </div>
            