
<div>
<h2>Donde estamos</h2>
<div style="width: 1200px">
    <iframe width="100%" height="600" src="https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;q=palacio%20nuevo%20de%20la%20finca%20de%20vista%20alegre+(Polideportivo)&amp;ie=UTF8&amp;t=&amp;z=16&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
    </iframe>
</div>
<br />
</div>