<div class="row">
<h2 class="text-center text-uppercase m-2">Donde estamos</h2>
    <div class="col-md-6">
    
    <div style="width: 1200px">
        <iframe width="60%" height="600" src="https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;q=palacio%20nuevo%20de%20la%20finca%20de%20vista%20alegre+(Polideportivo)&amp;ie=UTF8&amp;t=&amp;z=16&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
        </iframe>
    </div>
    <br />
    </div>
    <div class="col-md-3 col-md-offset-2 text-uppercase font-weight-bold" >
        <p><span class="text-primary">Direccion:</span> Palacio nuevo de la finca de vista alegre.</p>
        <p><span class="text-primary">WEB:</span> polideportivo.es</p>
        <p><span class="text-primary">Contacto:</span> polideportivo@gmail.com</p>
        <p><span class="text-primary">Telf:</span>9123583077</p>
        <p><span class="text-primary">Horario:</span> de 08:00 a 20:00</p>

    </div>
</div>