<h3>Estos son tus posts</h3>
<hr>
<?php foreach ($data as $post) {?>
	<div class="post">
		<h2> <?=$post->getTitulo() ?> </h2>
		<p> <?=$post->getContenido() ?> </p>
		<div>
			<span> <?=$post->getValoracion()?> ☆</span> - 
			<span> <?=$post->getEtiquetas()?> </span>
		</div>
		<div class="conf-post">
			<h4><a href="/foro/ver/<?=$post->getId()?>">Ver mas...</a></h4>
			<h4><a align="right" href="/foro/editar/<?=$post->getId()?>">Editar </a></h4>
		</div>
	</div>
<?php } ?>