<link rel="stylesheet" href="/css/reserva_pista.css">
<link rel="stylesheet" href="/css/reserva_clase.css">
    <div class="container">
        <div class="row">
          <div class="col-md-12">
            <main class=jumbotron>
              <h2 class="text-center text-uppercase">Reserva de pistas.</h2>
            <form action="/usuario/confirmar"method="post">

              <div class="form-group row">
                <label for="clases" class="col-sm-2 col-form-label">Fecha</label>
                <div class="col-sm-10">
                  <input type="date" name="fecha" min="01-01-2019" class="form-control">
                </div>
              </div>

               <div class="form-group row">
                <label for="clases" class="col-sm-2 col-form-label">Deportes</label>
                <div class="col-sm-10">
                  <select name="id_deporte" class="form-control">
                   <?php foreach ($data["deportes"] as $value) {?>
                      <option value=<?=$value['id_deporte']?>><?=$value['nombre_deporte']?></option>
                   <?php    
                  } ?>
                  </select>
                  
                </div>
              </div>
                <div class="form-group row">
                <label for="clases" class="col-sm-2 col-form-label">Horario</label>
                <div class="col-sm-10">
                  <select name="clases" class="form-control" multiple>
                    <option value="9">9:00 a 9:59</option>
                    <option value="11">11:00 a 11:59</option>
                    <option value="16">16:00 a 16:59</option>
                    <option value="19">19:00 a 19:59</option>
                  </select>
                </div>
              </div>

              <input type="submit" value="Enviar" class="btn btn-primary btn-block">

              <div class="pasos-reserva">
                <div class="row">
                  <div class="col-md-7 col-md-offset-3">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="col-md-4"><span class="circulo paso-actual">1</span></div>
                        <div class="col-md-4"><span class="circulo">2</span></div>
                        <div class="col-md-4"><span class="circulo">3</span></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              </div>
              
            </form>
              
            </main>
          </div>
        </div>
    </div>
