<link rel="stylesheet" href="/css/reservas.css">
<div>
    <h2 class="text-center text-uppercase" style="margin:20px 0;">Elige una de nuetros tipos de reservas</h2>
<div class="row text-center" id="reservas">
    <div class="col-md-6">
        <a href="/usuario/clasesDisponibles">Apuntate a nuestras clases<span><i class="fas fa-users"></i></span></a>
    </div>
    <div class="col-md-6">
        <a href="/usuario/reservarPista">Reserva una pista<span><i class="fas fa-swimmer"></i>    </span></a>
    </div>
</div>
</div>