<!-- <?=$data['form']?> -->
<?php $hoy = date('Y-m-d') ?>

<!-- CDN EDITOR -->
<script src="https://cdn.ckeditor.com/4.11.3/standard/ckeditor.js"></script>

<form action="#" method="post">
<input type="hidden" name="id">
    <div>
        <label for="titulo">Titulo</label>
        <input type="text" name="titulo" id="titulo">
    </div>
    <div>
        <textarea name="texto"></textarea>
    </div>
    <input type="hidden" name="fecha" value="<?= $hoy?>">
    <div>
        <input type="submit" value="Agregar noticia">
    </div>
</form>
<script>
    CKEDITOR.replace( 'texto' );
</script>

<a href="/noticias/list/">Volver al principio</a>