<div class="container" id="footer">
    <div class="row">
    <footer>
        <!-- Seccion explicativa -->
        <div class="col-md-10">
            <div class="row">
                <div class="col-md-3"><p><span class="span"><i class="fas fa-map-marker-alt"></i></span> Palacio V.Alegre. 54 28019 - Madrid</p></div>
                <div class="col-md-3"><p><span><i class="far fa-envelope"></i></span> polideportivo@gmail.com</p></div>
                <div class="col-md-3"><p><span><i class="fas fa-phone"></i></span> 9123583077</p></div>
                <div class="col-md-3"><p><span><i class="fas fa-mobile-alt"></i></span> 653445235</p></div>
            </div>
        </div>
        <!-- Iconos -->
        <div class="col-md-2 iconos">
            <div class="row">
                <div class="col-md-3"><a href=""><i class="fab fa-instagram"></i></a></div>
                <div class="col-md-3"><a href=""><i class="fab fa-linkedin"></i></a></div>
                <div class="col-md-3"><a href=""><i class="fab fa-facebook-square"></i></a></div>
                <div class="col-md-3"><a href=""><i class="fab fa-twitter-square"></i></a></div>
            </div>
        </div>
    </footer>
    </div>
</div>