 <nav>
 <ul class="navbar text-center">
            <div class="col-md-2" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/inicio" class="btn btn-block">Inicio</a>
                </li>
            </div>
            <div class="col-md-2" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/noticias" class="btn btn-block">Noticias</a>
                </li>
            </div>
            <div class="col-md-2" id="cols">
                <li class="nav-item active  ">
                    <a href="/usuario/localizacion" class="btn btn-block">Localizacion</a>
                </li>
            </div>
            <div class="col-md-2" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/reservas" class="btn btn-block">Reservas</a>
                </li>
            </div>
            <div class="col-md-1" id="cols">
                <li class="nav-item active ">
                    <a href="configuracion_perfil">
                    <i class="fas fa-user-cog" id="icon-user">edit</i></a>   
                </li>
            </div>
            <div class="col-md-1" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/logout">
                        <i class="fas fa-sign-out-alt" id="log-out">salir</i>
                    </a>
                </li>
            </div>
</ul>
 </nav>