<!-- <nav>
    <ul>
    <li><a href="#">
                        <div class="contenedor-logo">
                            <div class="logo">
                                <div class="circulo-peq">
                                    <div class="circulo-extra-peq">
                                        <div class="envoltorio">
                                            <div class="contenido">P</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
        <li><a href="/admin/inicio">inicio</a></li>
        <li><a href="/admin/empleados/">empleados</a></li>
        <li><a href="/admin/anadirClases">añadir clases</a></li>
        <li><a href="/admin/email">enviar correo</a></li>
    </ul>
</nav> -->
<div class="container" id="header">
<div class="row">
    <div class="col-md-3">
        <div class="contenedor-logo">
                <div class="logo">
                    <div class="circulo-peq">
                        <div class="circulo-extra-peq">
                            <div class="envoltorio">
                                <div class="contenido">P</div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    
        <div class="col-md-9 navbar" id="nav">

        <ul class="navbar text-center">
                    <div class="col-md-2" id="cols">
                        <li class="  nav-item active ">
                            <a href="/admin/inicio/" class="btn btn-block">Inicio</a>
                        </li>            
                    </div>
                    <div class="col-md-2" id="cols">
                        <li class=" nav-item active">
                            <a href="/admin/empleados/" class="btn btn-block">Empleados</a>
                        </li>
                    </div>
                    
                    <div class="col-md-2" id="cols">
                        <li class=" nav-item active">
                            <a href="/admin/anadirClases/" class="btn btn-block">Añadir clases</a>
                        </li>
                    </div>
                    <div class="col-md-2" id="cols">
                        <li class=" nav-item active">
                            <a href="/admin/email/" class="btn btn-block">Enviar correo</a>
                        </li>
                    </div>
                    <div class="col-md-1 col-md-offset-1" id="cols">
                        <li class="nav-item active ">
                            <a href="../../public/index.php">
                                <i class="fas fa-sign-out-alt" id="log-out"></i>
                            </a>
                        </li>
                    </div>
        </ul>
        </div>
    </div>

</div>