<nav>
    <ul>
    <li><a href="#">
                        <div class="contenedor-logo">
                            <div class="logo">
                                <div class="circulo-peq">
                                    <div class="circulo-extra-peq">
                                        <div class="envoltorio">
                                            <div class="contenido">P</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
        <li><a href="/admin/inicio">inicio</a></li>
        <li><a href="/admin/empleados/">empleados</a></li>
        <li><a href="/admin/anadirClases">añadir clases</a></li>
        <li><a href="/admin/email">enviar correo</a></li>
    </ul>
</nav>