
 <div class="container" id="header">
<div class="row">
    <div class="col-md-3">
        <div class="contenedor-logo">
                <div class="logo">
                    <div class="circulo-peq">
                        <div class="circulo-extra-peq">
                            <div class="envoltorio">
                                <div class="contenido">P</div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <div class="col-md-9 navbar" id="nav">
    <ul class="navbar text-center">
            <div class="col-md-2" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/inicio/" class="btn btn-block">Inicio</a>
                </li>
            </div>
            <div class="col-md-2" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/noticias/" class="btn btn-block">Noticias</a>
                </li>
            </div>
            <div class="col-md-2" id="cols">
                <li class="nav-item active  ">
                    <a href="/usuario/localizacion/" class="btn btn-block">Localizacion</a>
                </li>
            </div>
            <div class="col-md-2" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/reservas/" class="btn btn-block">Reservas</a>
                </li>
            </div>
            <div class="col-md-1" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/configuracion_perfil/">
                        <i class="fas fa-user-cog" id="icon-user"></i>
                    </a>   
                </li>
            </div>
            <div class="col-md-1" id="cols">
                <li class="nav-item active ">
                    <a href="/usuario/salir/">
                        <i class="fas fa-sign-out-alt" id="log-out"></i>
                    </a>
                </li>
            </div>
    </ul>
 
</div>
