<link rel="stylesheet" href="/css/anadirClases.css">
<?php

$hoy = date('Y-m-d');

?>

<div class="row" id="clase">
<h2 class="text-center">Añadir una clase</h2>
    <div class="col-md-6 col-md-offset-3">
    <form action="/admin/anadirClases" method="post">
            <div>
                <label for="id_clase">ID clase</label>
                <input type="text" name="id_clase" id="id_clase" required placeholder="CLASE-FUTBOL" class="form-control">
            </div>
            <div>
                <label for="fecha_hora">Fecha</label>
                <!-- <input type="date" name="fecha" id="fecha" min="<?= $hoy?>" required> -->
                <select name="fecha_hora" id="fecha_hora" class="form-control">
                <?php foreach ($data["horario"] as $index) { ?>
                    <option value="<?= $index["hora_inicio"]?>" > <?= $index["fecha"]?> ~ <?= $index["hora_inicio"]?> ~ <?= $index["hora_fin"]?> ~ <?= $index["id_pista"]?> </option>
                <?php }//forE ?>
                <input type="hidden" name="fecha" value="<?= $index["fecha"]?>">
                <input type="hidden" name="hora_inicio" value="<?= $index["hora_inicio"]?>">
                <input type="hidden" name="hora_fin" value="<?= $index["hora_fin"]?>">
                <input type="hidden" name="id_pista" value="<?= $index["id_pista"]?>">
                </select>
            </div>
            
            <div>
                <label for="nombre_clase">Nombre clase</label>
                <input type="text" name="nombre_clase" id="nombre_clase" required class="form-control">
            </div>
            <div>
                <label for="precio_clase">precio clase</label>
                <input type="text" name="precio_clase" id="precio_clase" required class="form-control">
            </div>
            <div>
                <label for="profesor">Profesor</label>
            <select name="id_usuario" required class="form-control">
                <?php foreach ($data["profesores"] as $index) { ?>
                    <option value="<?= $index["id_usuario"]?>" ><?= $index["nombre"]?>  (ID:<?= $index["id_usuario"]?>)</option>
                <?php }//forE ?>
            </select>
            </div>
            <div>
                <input type="submit" value="Agregar clase" class="btn btn-primary btn-block" style="margin-top:20px;">
                <a href="/admin/inicio" class="btn btn-block btn-danger">Cancelar</a>
            </div>

        </form>
    </div>
    
</div>

