<?php

$hoy = date('Y-m-d');

?>

<div >
    <form action="/admin/anadirClases" method="post">
        <div>
            <label for="id_clase">ID clase</label>
            <input type="text" name="id_clase" id="id_clase" required placeholder="CLASE-FUTBOL">
        </div>
        <div>
            <label for="fecha_hora">Fecha</label>
            <!-- <input type="date" name="fecha" id="fecha" min="<?= $hoy?>" required> -->
            <select name="fecha_hora" id="fecha_hora">
            <?php foreach ($data["horario"] as $index) { ?>
                <option value="<?= $index["hora_inicio"]?>"> <?= $index["fecha"]?> ~ <?= $index["hora_inicio"]?> ~ <?= $index["hora_fin"]?> ~ <?= $index["id_pista"]?> </option>
            <?php }//forE ?>
            <input type="hidden" name="fecha" value="<?= $index["fecha"]?>">
            <input type="hidden" name="hora_inicio" value="<?= $index["hora_inicio"]?>">
            <input type="hidden" name="hora_fin" value="<?= $index["hora_fin"]?>">
            <input type="hidden" name="id_pista" value="<?= $index["id_pista"]?>">
            </select>
        </div>
        
        <div>
            <label for="nombre_clase">Nombre clase</label>
            <input type="text" name="nombre_clase" id="nombre_clase" required>
        </div>
        <div>
            <label for="precio_clase">precio clase</label>
            <input type="text" name="precio_clase" id="precio_clase" required>
        </div>
        <div>
        <select name="id_usuario" required>
            <?php foreach ($data["profesores"] as $index) { ?>
                <option value="<?= $index["id_usuario"]?>"><?= $index["nombre"]?>  (ID:<?= $index["id_usuario"]?>)</option>
            <?php }//forE ?>
        </select>
        </div>
        <div>
            <input type="submit" value="Agregar clase">
            <a href="/admin/inicio">Cancelar</a>
        </div>

    </form>
</div>