<?php 
$estado = $data["pista"][0]["estado"];

$estado = ($estado == 0) ? false : true;
$pista = $data["pista"][0]["id_pista"];

    foreach ($data["pista"] as $value) { ?>
        <div class="row">
            <div class="col-md-9 col-md-offset-2">
            <h3 class="text-center text-uppercase">Actualizar datos de la pista: <?= $pista?></h3>
            <form action="#" method="post" class="jumbotron">
                <div>
                    <label for="nombre">Nombre de la pista:</label>
                    <input type="text" name="nombre_pista" placeholder="<?= $value["n_pista"]?>" class="form-control">
                </div>
                <div>
                    <label for="precio">Precio / Hora</label>
                    <input type="number" step="0.01" name="precio" placeholder="<?= $value["precio_hora"]?> €" class="form-control">
                </div>
                <label for="estado">Estado</label>
                <div class="form-check">
                    <input type="radio" class="form-check-input" id="disp" name="estado" value="1" <?php if($estado) echo "checked";?>>
                    <label class="form-check-label" for="disp">Disponible</label>
                </div>
                <div class="form-check">
                    <input type="radio" class="form-check-input" id="no_disp" name="estado" value="0"<?php if(!$estado) echo "checked";?>>
                    <label class="form-check-label" for="no_disp">No Disponible</label>
                </div>

                <div style="width:20em; margin: 10px auto; text-align:center;">
                    <input type="submit" value="Enviar" class="btn btn-primary ">
                    <a href="/admin/pistas/" class="btn btn-danger ">Cancelar</a>
                </div>
            </form>
            </div>
        
        </div>
    <?php }//forE


?>

