<?php 

$emails = "";

foreach ($data["datos_usuarios"] as $email) {
    $emails.=$email["email"]." - ";
}

?>


<div class="row">
    
    <div class="col-md-9 col-md-offset-2" style="padding:2em; box-shadow:0px 0px 10px #000; width:83em; margin:0 auto;">
    <h2 class="text-center text-uppercase">Envio de correos</h2>
        <form action="/admin/enviarEmail" method="post">
            <div>
                <label for="from">De:</label>
                <input type="text" name="from" id="from" value="polideportivo@gmail.com" readonly class="form-control">
            </div>
            <div>
                <label for="asunto">Asunto:</label>
                <input type="text" name="asunto" id="asunto" placeholder="Oferta de verano." class="form-control">
            </div>
            <div>
                <label for="contenido">Contenido</label>
                <input type="file" name="contenido" id="contenido" >
            </div>
            <div>
                <label for="to">TO:</label>
                <input type="text" name="emails" id="emails" value="<?= $emails?>" class="form-control">
            </div>
            <div >
                <input type="submit" value="Enviar" class="btn btn-block btn-primary" style="width:15em; margin:10px auto;">
            </div>
        </form>
    </div>
</div>