<?php $id = ""; ?>
<link rel="stylesheet" href="/css/listadoEmpleados.css">
<div class="row">
    <div class="col-md-11 col-md-offset-1">
        <form action="/admin/buscar/" method="post">
            <div class="col-md-3">
                <label for="nombre">Nombre</label>
                <input type="search" name="nombre" id="nombre" autofocus class="form-control">
            </div>
            <div class="col-md-3">
                <label for="apellido">Apellido</label>
                <input type="search" name="apellido" id="apellido" class="form-control">
            </div>
            <div class="col-md-3">
                <label for="dni">DNI</label>
                <input type="search" name="dni" id="dni" class="form-control">
            </div>
            <div class="col-md-2">
                <input type="submit" value="Enviar" class="btn btn-info btn-block">
            </div>
        </form>
    </div>
</div>

<div>
    <table class="table">
    <caption>Lista de Empleados</caption>
        <thead>
            <tr>
                <th>Id</th>
                <th>nombre</th>
                <th>primer apellido</th>
                <th>segundo apellido</th>
                <th>email</th>
                <th>nombre usuario</th>
                <th>sexo</th>
                <th>tipo usuario</th>
                <th>Borrar</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data["empleados"] as $value) { ?>
                <tr>
                <?php foreach ($value as $clave => $valor) { 
                    if ($clave == "sexo") 
                        $valor = ($clave == 0) ? "Masculino" : "Femenino";
                    if ($clave == "id_usuario") 
                        $id = $valor; ?>
                        <td><?= $valor?></td>
                        
                    <?php  }//forE ?>
                    <td><a href="/admin/borrar/<?= $id?>" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>
</a></td>
                </tr>
            <?php }//forE ?>
        </tbody>
    </table>
</div>
<a href="/admin/inicio/">Volver al principio</a>