<link rel="stylesheet" href="/css/listadoEmpleados.css">
<link rel="stylesheet" href="/css/mainAdmin.css">
<?php 

$total = implode("",$data[0]);
$admins = implode("",$data['admins'][0]);
$usuarios = implode("",$data['usuarios'][0]);

?>


<div class="row main-admin">
                <div class="col-md-4">
                    <a href="">
                    <div class="contenido-admin">
                            <h4>Numero usuarios</h4>
                            <span>
                                <i class="fas fa-users"></i>
                            </span>
                            <p><?= $total;?></p>
                            <p><span>Administradores: <?= $admins?></span></p>
                            <p><span>Clientes: <?= $usuarios?></span></p>
                    </div>
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="/admin/pistas/">
                        <div class="contenido-admin">
                            <h4>Editar pista</h4>
                            <span>
                                <i class="far fa-futbol"></i>
                            </span>
                        </div>
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="/noticias/add/">
                        <div class="contenido-admin">
                            <h4>Agregar noticias</h4>
                            <span>
                                <i class="far fa-newspaper"></i>
                            </span>
                        </div>
                    </a>
</div>





<div class="row">
    <div class="col-md-11 col-md-offset-1">
        <form action="/admin/buscar/" method="post">
            <div class="col-md-3">
                <label for="nombre">Nombre</label>
                <input type="search" name="nombre" id="nombre" autofocus class="form-control">
            </div>
            <div class="col-md-3">
                <label for="apellido">Apellido</label>
                <input type="search" name="apellido" id="apellido" class="form-control">
            </div>
            <div class="col-md-3">
                <label for="dni">DNI</label>
                <input type="search" name="dni" id="dni" class="form-control">
            </div>
            <div class="col-md-2">
                <input type="submit" value="Enviar" class="btn btn-info btn-block">
            </div>
        </form>
    </div>
</div>
<div>
    <table class="table">
    <caption>Lista de clientes.</caption>
        <thead class="text-white">
            <tr>
                <th>Id</th>
                <th>nombre</th>
                <th>primer apellido</th>
                <th>segundo apellido</th>
                <th>email</th>
                <th>sexo</th>
                <th>nacionalidad</th>
                <th>fecha nacimiento</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data["datos_usuarios"] as $value) { ?>
                <tr>
                <?php foreach ($value as $clave => $valor) { 
                    if ($clave == "sexo") 
                        $valor = ($clave == 0) ? "Masculino" : "Femenino"; ?>
                        <td><?= $valor?></td>
                    <?php  }//forE ?>
                </tr>
            <?php }//forE ?>
        </tbody>
    </table>
</div>