<link rel="stylesheet" href="/css/listadoEmpleados.css">
<link rel="stylesheet" href="/css/editarPista.css">

<?php 
$id_pista = "";
?>

<div>
    <h2 class="text-center font-weight-bold">Listado de pistas.</h2>
    <table class="table">
        <thead>
            <th>id pista</th>
            <th>nombre</th>
            <th>precio/hora</th>
            <th>id deporte</th>
            <th>id instala</th>
            <th>estado</th>
            <th>accion</th>
        </thead>
        <tbody>
        <?php foreach ($data["pistas"] as $value) { ?>
        <tr>
        <?php foreach ($value as $clave => $valor) { 
                if ($clave == "id_pista") $id_pista = $valor;
                
                if ($clave == "estado") 
                        $valor = ($valor == 0) ? "No Disponible" : "Disponible"; ?>
                <td><?= $valor?></td>
                
        <?php }//forE ?>
        
            <td>
                <a href="/admin/editar/<?= $id_pista?>" class="btn btn-warning">
                            <i class="fas fa-marker"></i> 
                </a>
            </td>
        </tr>
        <?php }//forE ?>
        </tbody>
    </table>
</div>