<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php $data['title']?></title>
</head>
<body>
<!-- Al ser el phtml base, se podra agregar el Js aqui, para todas las paginas que lo necesiten (desplegable del nav...) -->
    <?= $data['contenido']?>
</body>
</html>