<div class="container">
        <h1>Registro</h1>
        <div class="errList">
			<!-- LISTA DE ERRORES -->
			<?php if (count($errList) > 0) { ?> 
				<h3>Debe completar los campos</h3>
				<ul>
					<?php foreach ($errList as $key => $value) { ?>
						<li><?=$value?></li>
					<?php }//forE ?>
				</ul>
			<?php }//if ?>
        </div>
			<!-- FIN LISTA ERRORES -->
        <div class="form-group col-md-6 col-md-offset-3">
            <form action="#" method="post">
            <label for="dni">Dni:</label>
            <input type="text" name="dni" value="<?php // dni?>" class="form-control" pattern="[0-9]{8}[A-Za-z]{1}" maxlenght="9">
            <label for="nombre">Nombre:</label>
            <input type="text" name="nombre" value="<?php //$nombre?>" class="form-control">
            <label for="apellido_1">Primer apellido:</label>
            <input type="text" name="apellido_1" value="<?php // $apellido_1?>" class="form-control">
            <label for="apellido_2">Segundo Apellido:</label>
            <input type="text" name="apellido_2" value="<?php // $apellido_2?>" class="form-control">
            <label for="direccion">Direccion:</label>
            <input type="text" name="direccion" value="<?php // $direccion?>" class="form-control">
            <label for="sexo">Sexo: </label> &nbsp;
            <label for="hombre">Hombre</label>
            <input type="radio" name="sexo" value="hombre" class="radio-inline" <?php// if($sexo == "hombre") echo "checked"?>>
            <label for="hombre">Mujer</label>
            <input type="radio" name="sexo" value="mujer" class="radio-inline" <?php// if($sexo == "mujer") echo "checked"?>><br>
            <label for="email">Email:</label>
            <input type="email" name="email" value="<?php // $email?>" class="form-control">
            <label for="nacionalidad">Nacionalidad:</label>
            <input type="text" name="nacionalidad" value="<?php // $nacionalidad?>" class="form-control">
            <label for="nombre_usuario">Nombre usuario:</label>
            <input type="text" name="nombre_usuario" value="<?php // $nombre_usuario?>" class="form-control">
            <label for="contrasena">Contraseña:</label>
            <input type="password" name="contrasena" class="form-control">
            <label for="fecha_nacimiento">Fecha de nacimiento:</label>
            <input type="date" name="fecha_nacimiento" value="<?php // $fecha_nacimiento?>" class="form-control">

            <input type="submit" value="Enviar" name="enviar" class="btn btn-primary ">
            <a href="../../public/index.php" class="btn btn-danger">Cancelar</a>
        </form>
        </div>
    </div>